#ifndef _MCDMA_REGS_H_
#define _MCDMA_REGS_H_

#define MCDMA_BASE_ADDR 0x87000000
#define MCDMA_ADDR_RANGE (1 << 16)  // 64KB

// Comomn MM2S Register Offset
#define MCDMA_MM2S_CCR 0x000
#define MCDMA_MM2S_CSR 0x004
#define MCDMA_MM2S_CHEN 0x008
#define MCDMA_MM2S_CHSER 0x00C
#define MCDMA_MM2S_ERR 0x010
#define MCDMA_MM2S_CH_SCHD_TYPE 0x014
#define MCDMA_MM2S_WRR_REG1 0x018
#define MCDMA_MM2S_WRR_REG2 0x01C
#define MCDMA_MM2S_CHANNELS_SERVICED 0x020
#define MCDMA_MM2S_ARCACHE_ARUSER 0x024
#define MCDMA_MM2S_INTR_STATUS 0x028
// MM2S Common Control Register
// R/W • 0 = Reset not in progress. Normal operation. • 1 = Reset in progress.
#define MCDMA_MM2S_CCR_RST 0x00000004
// R/W  • 0 = Stop – MCDMA stops when current (if any) MCDMA operations are complete.
//      • 1 = Run  – Start MCDMA operations.
#define MCDMA_MM2S_CCR_RS 0x00000001
// MM2S Common Status Register
// R/O • 0 = MCDMA is not idle. • 1 = MCDMA is idle.
#define MCDMA_MM2S_CSR_IDLE 0x00000002
// R/O  • 0 = MCDMA channel running. • 1= MCDMA.RS bit is set to 0.
#define MCDMA_MM2S_CSR_HALTED 0x00000001

// Any Channel registers offset, CHX means CH1, CH2, etc
#define MCDMA_MM2S_CHAN_CR 0x00
#define MCDMA_MM2S_CHAN_SR 0x04
#define MCDMA_MM2S_CHAN_CURDESC_LSB 0x08
#define MCDMA_MM2S_CHAN_CURDESC_MSB 0x0C
#define MCDMA_MM2S_CHAN_TAILDESC_LSB 0x10
#define MCDMA_MM2S_CHAN_TAILDESC_MSB 0x14
#define MCDMA_MM2S_CHAN_PKTCOUNT_STAT 0x18
// Channel register bits
#define MCDMA_MM2S_CHAN_CR_FETCH_MASK 0x1
#define MCDMA_MM2S_CHAN_CR_IOC_IRQEN_MASK (0x1 << 5)
#define MCDMA_MM2S_CHAN_SR_IDLE_MASK 0x1
#define MCDMA_MM2S_CHAN_SR_IOC_IRQ_MASK (0x1 << 5)
// MM2S channel register base addr
#define MCDMA_MM2S_CHX_REG_ADDR_RANGE 0x40
#define MCDMA_MM2S_CH1_BASE_ADDR 0x040
#define MCDMA_MM2S_CH2_BASE_ADDR 0x080
#define MCDMA_MM2S_CH3_BASE_ADDR 0x0C0
#define MCDMA_MM2S_CH4_BASE_ADDR 0x100
#define MCDMA_MM2S_CH5_BASE_ADDR 0x140
#define MCDMA_MM2S_CH6_BASE_ADDR 0x180
#define MCDMA_MM2S_CH7_BASE_ADDR 0x1C0
#define MCDMA_MM2S_CH8_BASE_ADDR 0x200
#define MCDMA_MM2S_CH9_BASE_ADDR 0x240
#define MCDMA_MM2S_CH10_BASE_ADDR 0x280

/***
 * All Registers in each MM2S channels
 */
#define MCDMA_MM2S_CHX_REG(chan, regoffset)                                                        \
  (MCDMA_MM2S_CH1_BASE_ADDR + regoffset + (chan * MCDMA_MM2S_CHX_REG_ADDR_RANGE))
#define MCDMA_MM2S_CHX_CR(chan) MCDMA_MM2S_CHX_REG(chan, MCDMA_MM2S_CHAN_CR)
#define MCDMA_MM2S_CHX_SR(chan) MCDMA_MM2S_CHX_REG(chan, MCDMA_MM2S_CHAN_SR)
#define MCDMA_MM2S_CHX_CURDESC_LSB(chan) MCDMA_MM2S_CHX_REG(chan, MCDMA_MM2S_CHAN_CURDESC_LSB)
#define MCDMA_MM2S_CHX_CURDESC_MSB(chan) MCDMA_MM2S_CHX_REG(chan, MCDMA_MM2S_CHAN_CURDESC_MSB)
#define MCDMA_MM2S_CHX_TAILDESC_LSB(chan) MCDMA_MM2S_CHX_REG(chan, MCDMA_MM2S_CHAN_TAILDESC_LSB)
#define MCDMA_MM2S_CHX_TAILESC_MSB(chan) MCDMA_MM2S_CHX_REG(chan, MCDMA_MM2S_CHAN_TAILDESC_MSB)
#define MCDMA_MM2S_CHX_PKTCOUNT_STAT(chan) MCDMA_MM2S_CHX_REG(chan, MCDMA_MM2S_CHAN_PKTCOUNT_STAT)

// Comomn S2MM Register Offset
#define MCDMA_S2MM_CCR 0x500
#define MCDMA_S2MM_CSR 0x504
#define MCDMA_S2MM_CHEN 0x508
#define MCDMA_S2MM_CHSER 0x50C
#define MCDMA_S2MM_ERR 0x510
#define MCDMA_S2MM_PKTDROP 0x514
#define MCDMA_S2MM_CHANNELS_SERVICED 0x518
#define MCDMA_S2MM_ARCACHE_ARUSER 0x51C
#define MCDMA_S2MM_INTR_STATUS 0x520
// S2MM Common Control Register
// R/W • 0 = Reset not in progress. Normal operation. • 1 = Reset in progress.
#define MCDMA_S2MM_CCR_RST 0x00000004
// R/W  • 0 = Stop – MCDMA stops when current (if any) MCDMA operations are complete.
//      • 1 = Run  – Start MCDMA operations.
#define MCDMA_S2MM_CCR_RS 0x00000001
// S2MM Common Status Register
// R/O • 0 = MCDMA is not idle. • 1 = MCDMA is idle.
#define MCDMA_S2MM_CSR_IDLE 0x00000002
// R/O  • 0 = MCDMA channel running. • 1= MCDMA.RS bit is set to 0.
#define MCDMA_S2MM_CSR_HALTED 0x00000001

// Any Channel registers offset, CHX means CH1, CH2, etc
#define MCDMA_S2MM_CHAN_CR 0x00
#define MCDMA_S2MM_CHAN_SR 0x04
#define MCDMA_S2MM_CHAN_CURDESC_LSB 0x08
#define MCDMA_S2MM_CHAN_CURDESC_MSB 0x0C
#define MCDMA_S2MM_CHAN_TAILDESC_LSB 0x10
#define MCDMA_S2MM_CHAN_TAILDESC_MSB 0x14
#define MCDMA_S2MM_CHAN_PKTDROP_STAT 0x18
#define MCDMA_S2MM_CHAN_PKTCOUNT_STAT 0x1C

#define MCDMA_S2MM_CHAN_CR_FETCH_MASK 0x1
#define MCDMA_S2MM_CHAN_CR_IOC_IRQEN_MASK (0x1 << 5)
#define MCDMA_S2MM_CHAN_SR_IDLE_MASK 0x1
#define MCDMA_S2MM_CHAN_SR_IOC_IRQ_MASK (0x1 << 5)
// S2MM channel register base addr
#define MCDMA_S2MM_CHX_REG_ADDR_RANGE 0x40
#define MCDMA_S2MM_CH1_BASE_ADDR 0x540
#define MCDMA_S2MM_CH2_BASE_ADDR 0x580
#define MCDMA_S2MM_CH3_BASE_ADDR 0x5C0
#define MCDMA_S2MM_CH4_BASE_ADDR 0x600
#define MCDMA_S2MM_CH5_BASE_ADDR 0x640
#define MCDMA_S2MM_CH6_BASE_ADDR 0x680
#define MCDMA_S2MM_CH7_BASE_ADDR 0x6C0
#define MCDMA_S2MM_CH8_BASE_ADDR 0x700
#define MCDMA_S2MM_CH9_BASE_ADDR 0x740
#define MCDMA_S2MM_CH10_BASE_ADDR 0x780
/***
 * All Registers in each S2MM channels
 */
#define MCDMA_S2MM_CHX_REG(chan, regoffset)                                                        \
  (MCDMA_S2MM_CH1_BASE_ADDR + regoffset + (chan * MCDMA_S2MM_CHX_REG_ADDR_RANGE))
#define MCDMA_S2MM_CHX_CR(chan) MCDMA_S2MM_CHX_REG(chan, MCDMA_S2MM_CHAN_CR)
#define MCDMA_S2MM_CHX_SR(chan) MCDMA_S2MM_CHX_REG(chan, MCDMA_S2MM_CHAN_SR)
#define MCDMA_S2MM_CHX_CURDESC_LSB(chan) MCDMA_S2MM_CHX_REG(chan, MCDMA_S2MM_CHAN_CURDESC_LSB)
#define MCDMA_S2MM_CHX_CURDESC_MSB(chan) MCDMA_S2MM_CHX_REG(chan, MCDMA_S2MM_CHAN_CURDESC_MSB)
#define MCDMA_S2MM_CHX_TAILDESC_LSB(chan) MCDMA_S2MM_CHX_REG(chan, MCDMA_S2MM_CHAN_TAILDESC_LSB)
#define MCDMA_S2MM_CHX_TAILDESC_MSB(chan) MCDMA_S2MM_CHX_REG(chan, MCDMA_S2MM_CHAN_TAILDESC_MSB)
#define MCDMA_S2MM_CHX_PKTDROP_STAT(chan) MCDMA_S2MM_CHX_REG(chan, MCDMA_S2MM_CHAN_PKTDROP_STAT)
#define MCDMA_S2MM_CHX_PKTCOUNT_STAT(chan) MCDMA_S2MM_CHX_REG(chan, MCDMA_S2MM_CHAN_PKTCOUNT_STAT)

#endif